program: train.py
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  dropout:
    values: [0.15, 0.2, 0.25, 0.3, 0.4]

  batch_size:
    values: [64, 128, 256]

  learning_rate:
    values: [0.0005, 0.001, 0.005]

  base_channels:
    values: [16, 32, 64]

  channel_mult:
    values: [1, 2, 3]

  n_conv_layers:
    values: [6, 8, 10]

  apply_dropout_at:
    values: [1, 2, 3]

  activation:
    values: ["ReLU", "GELU", "SiLU"]

  kernel_size:
    values: [3]
  stride:
    values: [2]
  padding:
    values: [1]

  epochs:
    value: 30

# Uses uv package management
command:
  - ${env}
  - uv
  - run
  - python
  - train.py
  - ${args}