program: train.py
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  dropout:
    values: [0.2, 0.3]

  batch_size:
    values: [64, 128]

  learning_rate:
    values: [0.0005, 0.001]

  base_channels:
    values: [32, 64]

  channel_mult:
    values: [2, 3]

  n_conv_layers:
    values: [2, 3, 5]

  apply_dropout_at:
    values: [2]

  activation:
    values: ["ReLU", "GELU", "SiLU"]

  kernel_size:
    values: [3]
  stride:
    values: [2]
  padding:
    values: [1]
  max_channels:
    values: [128]
  seed:
    values: [42]

  epochs:
    value: 30

# Uses uv package management
command:
  - ${env}
  - uv
  - run
  - python
  - train.py
  - ${args}