program: train.py
method: bayes
metric:
  goal: minimize
  name: val_loss

parameters:
  # VAE Architecture parameters
  latent_dim:
    values: [7, 13, 21, 28, 49]

  base_channels:
    values: [16, 24, 32]

  blocks_per_level:
    values: [1, 2, 3]

  groups:
    values: [1, 2, 4]

  dropout:
    min: 0.2
    max: 0.6
    distribution: uniform

  activation:
    values: ['GELU', 'ReLU', 'SiLU', 'LeakyReLU']

  # Training parameters
  batch_size:
    values: [128, 256]

  learning_rate:
    min: 0.0001
    max: 0.01
    distribution: log_uniform_values

  weight_decay:
    min: 0.000001
    max: 0.0001
    distribution: log_uniform_values

  beta_final:
    min: 0.1
    max: 3.0
    distribution: uniform

  warmup_epochs:
    values: [5, 10]

  # Fixed parameters
  epochs:
    value: 25

  ema:
    value: 0.97

# Command to run (uses uv if available)
#command:
#  - ${env}
#  - uv
#  - run
#  - python
#  - ${program}
#  - ${args}